cypress-shared/support/common/commands.js, cypress-shared/support/common/support.js
1. Added verifyTotal command in commands.js
2. Improved regex
3. Removed unused updateInvalidShippingInformation()
4. Removed below code from orderAndSaveProductId()
```
cy.promissoryPayment()
cy.buyProduct()
```
=> Cyrunner improvements

cypress-shared/integration/b2b/wipe.spec.js, cypress-shared/support/b2b/checkout.js, cypress-shared/support/b2b/common.js, cypress-shared/support/b2b/cost_center.js, cypress-shared/support/b2b/login.js, cypress-shared/support/b2b/utils.js, cypress-shared/support/common/selectors.js
1. Use workspace name with user email id
2. Store userAuthCookie on login - If testcase gets failed then next time use than to login
3. To delete user in wipe -use workspace name as a key.
4. Look text save in button element
=> Parallelization over B2B apps

node/cypress/integration/vtex-auth.spec.js
Sample Link: https://github.com/vtex/connector-paypal-commerce-platform/runs/5687777443?check_suite_focus=true
=> Add 2 second delay in vtex-auth.spec.js

cypress-shared/support/common/refund_apis.js, cypress-shared/support/common/support.js, cypress-shared/support/common/utils.js
1. Updated refund() to accept payload function as a parameter
2. setProductQuantity() -> added timeout option
3. After searching for a product, ensure search text is visible in screen once it is visible look for filter Heading.
4. Added greenconventional product(promotional) in utils.js
=> Updated code to support cybersource

cypress-shared/support/b2b/common.js, node/utils.js, node/workspace.js, package.json, yarn.lock
Added 2 validations on sessions
Logging on cypress the list of apps and its deps
=> Added app list and deps

cypress-shared/support/common/testcase.js
if workspace is configured to taxConfiguration, then that workspace only can set taxConfiguration back to null
=> Fix OrderForm Tax Configuration Logic

cypress-shared/support/b2b/add_users.js, cypress-shared/support/b2b/common.js, cypress-shared/support/b2b/utils.js
https://github.com/vtex-apps/b2b-organizations/actions/runs/2588315693
=> Improve setOrganizationIdInJSON

cypress-shared/support/common/support.js
For now, This is used in paypal
=> Add option to select shipping strategy

cypress-shared/support/extract.js, cypress-shared/support/gmail.js, node/cypress/integration/vtex-auth.spec.js
In Fedex Shipping, we would be using vtex email
https://github.com/vtex-apps/fedex-shipping/actions/runs/2816676890
I also tested this code with non vtex email
https://github.com/vtex-apps/shopper-location/actions/runs/2816916473
=> Support vtex email in vtex auth

CHANGELOG.md, cypress-shared/integration/b2b/2.12-organization_admin_scenarios-orgA.spec.js, cypress-shared/integration/b2b/2.13-sales_manager_scenarios.spec.js, cypress-shared/integration/b2b/2.14-sales_rep_scenarios.spec.js, cypress-shared/integration/b2b/2.8-sales_admin_scenarios.spec.js, cypress-shared/support/b2b/organization_request.js
a) Reorder/sales user cypress tests
b) Reorder organization admin cypress tests
=> Reorder sales user / organization admin cypress tests

CHANGELOG.md, cypress-shared/integration/shopper-location/2.1-test-locale-redirect-configuration.spec.js, cypress-shared/support/shopper-location/outputvalidation.js
Update validation to match latest response
=> Update validation to match latest response

CHANGELOG.md, cypress-shared/integration/shopper-location/2.1-test-locale-redirect-configuration.spec.js, cypress-shared/support/common/selectors.js, cypress-shared/support/shopper-location/common.js, cypress-shared/support/shopper-location/outputvalidation.js, node/report.js
Improve Shopper Location Testcase - Handle both province dropdown and text field
=> Improve Shopper Location Testcase - Handle both province dropdown and text field

CHANGELOG.md, cypress-shared/integration/b2b/2.4-add-remaining-users.spec.js, cypress-shared/support/b2b/add_users.js, cypress-shared/support/b2b/checkout.js, cypress-shared/support/b2b/organization_request.js, cypress-shared/support/b2b/quick_order.js, cypress-shared/support/b2b/quotes.js
1. Replace {retries: } with updateRetry
2. Fix 2.4 title
3. For create quotes, 20 seconds timeout
4. Use force true for button click
=> Improve b2b tests

cypress-shared/support/shopper-location/common.js
For province, use last input text field selector
=> For province, use last input text field selector - #trivial

cypress-shared/support/location-availability/common.js
Verify shipping section in 2.8 testcase - #trivial
=> Verify shipping section in 2.8 testcase - #trivial

cypress-shared/support/common/selectors.js
=> added shippinginfo selector - #trivial

cypress-shared/support/common/support.js
=> Fix/shipping information - #trivial

CHANGELOG.md, cypress-shared/support/common/support.js
Added 10s delay in update shipping information
=> Added 10s delay in update shipping information

cypress-shared/support/common/support.js
Click cart timeline in shipping info - #trivial
=> Click cart timeline in shipping info - #trivial

CHANGELOG.md, cypress-shared/support/adyen/testcase.js
[ENGINEERS-831] - Use log false for cy.type command
[ENGINEERS-831]: https://vtex-dev.atlassian.net/browse/ENGINEERS-831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENGINEERS-831] - Use log false for cy.type command

CHANGELOG.md, cypress-shared/integration/location-availability/2.5-Add-multiple-pickuppoint-and-update-shipping.spec.js, cypress-shared/integration/location-availability/wipe.spec.js, cypress-shared/support/common/apis.js, cypress-shared/support/common/shipping-policy.graphql.js
Updated shipping strategy function to use multiple places
=> moving update shipping strategy function to common folder

CHANGELOG.md, cypress-shared/support/common/support.js
=> [ENGINEERS-886] - Removed cartTimeline click

CHANGELOG.md, cypress-shared/support/common/checkout_ui_custom.js, cypress-shared/support/common/testcase.js
Added checkout ui custom configuration
=> [ENGINEERS-911] - Added checkout ui custom configuration

CHANGELOG.md, cypress-shared/integration/shopper-location/2.3-disable-location-via-browser-popup-order-product.spec.js, cypress-shared/integration/shopper-location/2.4-enable-Location-via-browser-popup-order-product.spec.js, cypress-shared/integration/shopper-location/wipe.spec.js, cypress-shared/support/shopper-location/common.js, cypress-shared/support/shopper-location/outputvalidation.js
changes in 2.3,2.4 & added wipe
=> ENGINEERS-912-changes in 2.3,2.4 & added wipe

CHANGELOG.md, cypress-shared/support/common/refund_apis.js, cypress-shared/support/common/support.js
Prepend empty characters in address line
=> [ENGINEERS-924] - Prepend empty characters in address line

CHANGELOG.md, cypress-shared/integration/affirm/2.4-discountProduct.spec.js, cypress-shared/integration/affirm/2.7-transactions.spec.js, cypress-shared/integration/affirm/post_setup.spec.js, cypress-shared/integration/affirm/wipe.spec.js, cypress-shared/support/affirm/outputvalidation.js, cypress-shared/support/affirm/testcase.js, cypress-shared/support/common/testcase.js
- Added cancellation scenario testcase
=> Affirm payments cancellation test

cypress-shared/integration/adyen/2.3-multiProduct.spec.js, cypress-shared/integration/adyen/2.5-externalSeller.spec.js, cypress-shared/support/common/support.js
Improve filling shipping information
=> Improve filling shipping information - #trivial

CHANGELOG.md, cypress-shared/support/b2b/checkout.js, cypress-shared/support/b2b/common.js, cypress-shared/support/commands.js
=> [ENGINEERS-975] - Improve b2b checkout tests

CHANGELOG.md, cypress-shared/integration/fedex-shipping/2.3-single-product-scenarios.spec.js, cypress-shared/integration/fedex-shipping/2.4-multi-product-scenarios.spec.js, cypress-shared/integration/fedex-shipping/2.8-shipping-optimize-scenarios.spec.js
- Imrpoved single & multi product test cases
- Increased delay between retries in 2.8
=> [ENGINEERS-972] - Fedex quick fixes

CHANGELOG.md, cypress-shared/integration/affirm/2.4-discountProduct.spec.js, cypress-shared/support/affirm/testcase.js, cypress-shared/support/common/selectors.js
- Improved affirm selectors
- Verifying order status should be ***handling*** before canceling
=> [ENGINEERS-976, ENGINEERS-985, ENGINEERS-986 ] - Affirm Payments selectors improvements

CHANGELOG.md, cypress-shared/support/common/support.js
- Paypal checkout issue fixed.
=> [ENGINEERS-994] - Paypal quick fixes

cypress-shared/support/b2b/checkout.js, cypress-shared/support/b2b/quotes.js, cypress-shared/support/quick-order/testcase.js
=> B2B Checkout Improvements - #trivial

CHANGELOG.md, cypress-shared/integration/b2b/2.1.2-multi_organizations_requests_from_organizationB.spec.js, cypress-shared/support/b2b/organization_request.js
- Drop duplicate organization request testcase
=> [ENGINEERS-1033] - Drop duplicate organization request testcase

CHANGELOG.md, cypress-shared/integration/affirm/post_setup.spec.js, cypress-shared/support/affirm/graphql_testcase.js, cypress-shared/support/common/selectors.js
=> [ENGINEERS-1037] - Added affirm promo test

CHANGELOG.md, cypress-shared/integration/b2b/2.1.3-organization_negative_testcases.spec.js
[ENGINEERS-1058] - Don't login with the user which we would be assigning to a b2b organization
[ENGINEERS-1058]: https://vtex-dev.atlassian.net/browse/ENGINEERS-1058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENGINEERS-1058] - Don't login with the user which we would be assigning to a b2b organization

CHANGELOG.md, cypress-shared/integration/b2b/2.1.2-multi_organizations_requests_from_organizationB.spec.js, cypress-shared/integration/b2b/2.12.1-sales_admin_scenarios.spec.js, cypress-shared/integration/b2b/2.12.2-sales_admin_scenarios.spec.js, cypress-shared/integration/b2b/2.13.1-sales_manager_scenarios.spec.js, cypress-shared/integration/b2b/2.13.2-sales_manager_scenarios.spec.js, cypress-shared/integration/b2b/2.14.1-sales_rep_scenarios.spec.js, cypress-shared/integration/b2b/2.14.2-sales_rep_scenarios.spec.js, cypress-shared/support/b2b/common.js, cypress-shared/support/b2b/impersonation_quote_access.js, cypress-shared/support/b2b/quotes.js, cypress-shared/support/commands.js
- Drop a testcase from 2.1.2 and B2B improvements
=> [ENGINEERS-1062] - Drop a testcase from 2.1.2 and B2B improvements

CHANGELOG.md, cypress-shared/support/commands.js, cypress-shared/support/location-availability/support.js, cypress-shared/support/shopper-location/common.js
Improvement of shopper location & location availability.
=> [ENGINEERS-1073] - Improvement of shopper location & location availability.

CHANGELOG.md, cypress-shared/support/common/refund_apis.js
- Added sendInvoice testcase in refund
=> Added sendInvoice testcase in refunds

CHANGELOG.md, cypress-shared/integration/location-availability/2.1-disable-location-and-test.spec.js, cypress-shared/integration/location-availability/2.2-enable-location-and-test.spec.js, cypress-shared/integration/location-availability/2.3-location-availability.spec.js, cypress-shared/integration/location-availability/2.4-location-not-available.spec.js, cypress-shared/integration/location-availability/2.5-Add-multiple-pickuppoint-and-update-shipping.spec.js, cypress-shared/integration/location-availability/wipe.spec.js, cypress-shared/integration/quick-order/1.1-graphql.spec.js, cypress-shared/integration/quick-order/1.2.1-skucode_quantity.spec.js, cypress-shared/integration/quick-order/1.3.1-upload_csv.spec.js, cypress-shared/integration/quick-order/1.3.3_download-spreadsheet_verify_data&extension.spec.js, cypress-shared/integration/shopper-location/2.1-test-locale-redirect-configuration.spec.js, cypress-shared/integration/shopper-location/2.2-test-locale-with-autoredirect.spec.js, cypress-shared/integration/shopper-location/2.5-negative-scenarios-with-location.spec.js, cypress-shared/integration/shopper-location/2.6-negative-scenarios-disable-location.spec.js, cypress-shared/support/b2b/quotes.js, cypress-shared/support/b2b/utils.js, cypress-shared/support/commands.js, cypress-shared/support/common/commands.js, cypress-shared/support/common/support.js, cypress-shared/support/common/testcase.js, cypress-shared/support/location-availability/support.js, cypress-shared/support/quick-order/testcase.js, cypress-shared/support/shopper-location/common.js, cypress-shared/support/shopper-location/settings.js
Added cy.qe command to store logs
=> [ENGINEERS-1065] - Added cy.qe command for write logs

CHANGELOG.md, cypress-shared/support/common/commands.js, cypress-shared/support/common/support.js
- beforeEach block to add testcase title
=> [ENGINEERS-1156] - beforeEach block to add testcase title

CHANGELOG.md, cypress-shared/integration/fedex-shipping/2.1-graphql.spec.js, cypress-shared/integration/fedex-shipping/2.5-hide-sla-scenarios.spec.js, cypress-shared/integration/fedex-shipping/2.6-show-sla-scenarios.spec.js, cypress-shared/integration/fedex-shipping/2.9-validate-shipping-from-different-origins.spec.js, cypress-shared/support/common/api_commands.js, cypress-shared/support/common/commands.js, cypress-shared/support/common/constants.js, cypress-shared/support/common/support.js, cypress-shared/support/fedex-shipping/api_testcase.js, cypress-shared/support/fedex-shipping/graphql_testcase.js
Added fedex logs + graphqlLogs command
=> [ENGINEERS-1155] - Added fedex logs + graphqlLogs command

CHANGELOG.md, cypress-shared/support/b2b/common.js, cypress-shared/support/b2b/graphql.js
- Improve sessions validation & add delay between retries to handle slow responses
=> [ENGINEERS-1173] - Improve sessions validation & add delay between retries to handle slow responses

CHANGELOG.md, cypress-shared/integration/b2b/2.4.2-hide_organization_by_adding_dolar_sales_channel.spec.js, cypress-shared/support/b2b/common.js, cypress-shared/support/common/commands.js
- Improve session validations in all places
=> [ENGINEERS-1173] - Improve session validations in all places

CHANGELOG.md, cypress-shared/support/b2b/common.js, cypress-shared/support/b2b/cost_center.js, cypress-shared/support/b2b/graphql.js, cypress-shared/support/b2b/login.js, cypress-shared/support/b2b/organization_request.js, cypress-shared/support/b2b/utils.js, cypress-shared/support/commands.js, cypress-shared/support/common/commands.js, cypress-shared/support/common/support.js
- Added logs for organization creation testcases
=> [ENGINEERS-1148] - Added logs for organization creation testcases

CHANGELOG.md, cypress-shared/support/common/support.js
- Increasse delay for address type
=> Increasse delay for address type

CHANGELOG.md, node/config.js
- Added CI in cypress vtex environment variables
=> Added CI in cypress vtex environment variables

CHANGELOG.md, cypress-shared/support/commands.js
=> Fix 2.8 testcase

CHANGELOG.md, cypress-shared/support/common/support.js
- Fix updateShipping information
=> Fix updateShipping information

CHANGELOG.md, cypress-shared/support/common/testcase.js
- Fix syncCheckoutUICustom testcase
=> Fix syncCheckoutUICustom testcase
